services:
  # node-bootstrap:                     # optional, local themes and icons
  #   image: aceberg/node-bootstrap
  #   container_name: node-bootstrap
  #   restart: unless-stopped
  #   ports:
  #   - 8850:8850
  watchyourlan:
    image: ghcr.io/gbomacfly/watchyourlan # GitHub Container Registry
    container_name: watchyourlan
    network_mode: "host"
    restart: unless-stopped
    # uncomment those if you are using local node-bootstrap:
    # command: "-n http://YOUR_IP:8850"   # put your server IP or DNS name here
    # depends_on:
    #   - node-bootstrap
    volumes:
    - ~/.dockerdata/watchyourlan:/data/WatchYourLAN
    environment:
      TZ: "YOUR_TIMEZONE"    # required: needs your TZ for correct time, e.g. "Europe/Berlin"
      IFACES: "YOUR_IFACE"   # required: 1 or more interface, space separated
      # HOST: "0.0.0.0"        # optional, default: 0.0.0.0
      # PORT: "8840"            # optional, default: 8840
      # TIMEOUT: "120"          # optional, time in seconds, default: 120
      # SHOUTRRR_URL: ""        # optional, set url to notify
      # THEME: "cyborg"         # optional
      # COLOR: "system"         # optional
